DROP TABLE IF EXISTS "companies" CASCADE;
DROP TABLE IF EXISTS "licences" CASCADE;
DROP TABLE IF EXISTS "devices" CASCADE;
DROP TABLE IF EXISTS "licence_types" CASCADE;
DROP TABLE IF EXISTS "licences_devices" CASCADE;

